// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG8aFQWYdYNKSFUXsDKd7fE7oR01VLskw',
    appId: '1:249968013432:web:76500fdb25dc57f841bd8d',
    messagingSenderId: '249968013432',
    projectId: 'inuny-5541c',
    authDomain: 'inuny-5541c.firebaseapp.com',
    storageBucket: 'inuny-5541c.appspot.com',
    measurementId: 'G-P13WET88B0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyuJRzWY1N6i2c5qyHjBCOVy-0HLhjmpo',
    appId: '1:249968013432:android:112a3cd661fac56841bd8d',
    messagingSenderId: '249968013432',
    projectId: 'inuny-5541c',
    storageBucket: 'inuny-5541c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy0Pn_QwMqS7apd1KqIkYmPGozV98xO0E',
    appId: '1:249968013432:ios:35686a68b756822641bd8d',
    messagingSenderId: '249968013432',
    projectId: 'inuny-5541c',
    storageBucket: 'inuny-5541c.appspot.com',
    iosClientId: '249968013432-nedvdgouvbspjvgfkn1vrnddm3e8p8l6.apps.googleusercontent.com',
    iosBundleId: 'com.example.inunyTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy0Pn_QwMqS7apd1KqIkYmPGozV98xO0E',
    appId: '1:249968013432:ios:35686a68b756822641bd8d',
    messagingSenderId: '249968013432',
    projectId: 'inuny-5541c',
    storageBucket: 'inuny-5541c.appspot.com',
    iosClientId: '249968013432-nedvdgouvbspjvgfkn1vrnddm3e8p8l6.apps.googleusercontent.com',
    iosBundleId: 'com.example.inunyTest',
  );
}
